import './globals.css';
import type { Metadata } from 'next';
import { Raleway, Roboto } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { PostHogProvider } from './providers'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  display: 'swap',
});

const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${raleway.variable}`}>
      <body className="font-roboto antialiased">
        <Toaster />
        <PostHogProvider>
          {children}
        </PostHogProvider>
      </body>
    </html>
  );
}
