name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PRs
        uses: pascalgn/automerge-action@v0.15.3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: squash