name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'dependencies') &&
      github.event.pull_request.title =~ /^Bump.*(patch|minor)$/
    steps:
      - uses: pascalgn/automerge-action@v0.15.3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: squash