name: Lint & Format Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # needed to push commits

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Auto-fix ESLint issues
        run: |
          npm run lint:fix
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: auto-fix lint issues" || echo "No lint fixes"
          
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          git push origin HEAD:$BRANCH_NAME --force-with-lease

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Auto-fix Prettier issues
        run: |
          npm run format:fix
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: auto-fix format issues" || echo "No format fixes"
          
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          git push origin HEAD:$BRANCH_NAME --force-with-lease
